//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxCrypt.Content.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LongResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LongResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxCrypt.Content.Properties.LongResources", typeof(LongResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///@{
        ///    Layout = &quot;Template_EmailLayout_cshtml&quot;;
        ///    var ActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate?Email=&quot; + Model.UserName + &quot;&amp;Code=&quot; + Model.ActivationCode;
        ///    var ManualActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate&quot;;
        ///}
        ///&lt;table style=&quot;padding: 20px; width: 100%;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td /&gt;
        ///        &lt;td style=&quot;padding: 20px; margin: 0 auto !important; background-color: #ffffff; border: 1px solid #f0f0f0; display: block !import [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_ActivateEmail_cshtml {
            get {
                return ResourceManager.GetString("Template_ActivateEmail_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///@{
        ///    Layout = &quot;Template_EmailLayout_cshtml&quot;;
        ///    var ActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate?Email=&quot; + Model.UserName + &quot;&amp;Code=&quot; + Model.ActivationCode;
        ///    var ManualActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate&quot;;
        ///}
        ///&lt;table style=&quot;padding: 20px; width: 100%;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td /&gt;
        ///        &lt;td style=&quot;padding: 20px; margin: 0 auto !important; background-color: #ffffff; border: 1px solid #f0f0f0; display: block !import [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_AppActivateEmail_cshtml {
            get {
                return ResourceManager.GetString("Template_AppActivateEmail_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///@{
        ///    Layout = null;
        ///    var ActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate?Email=&quot; + Model.UserName + &quot;&amp;Code=&quot; + Model.ActivationCode;
        ///    var ManualActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate&quot;;
        ///}
        ///Hello and Welcome to AxCrypt,
        ///
        ///You have signed up for an AxCrypt account.
        ///
        ///To complete activation in the application please enter the activation code into the application.
        ///
        ///Your activation code is @Model.ActivationCode .
        ///
        ///You [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_AppActivateEmailPlainText_cshtml {
            get {
                return ResourceManager.GetString("Template_AppActivateEmailPlainText_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///@{
        ///    Layout = &quot;Template_EmailLayout_cshtml&quot;;
        ///    var ActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate?Email=&quot; + Model.UserName + &quot;&amp;Code=&quot; + Model.ActivationCode;
        ///}
        ///&lt;table style=&quot;padding: 20px; width: 100%;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td /&gt;
        ///        &lt;td style=&quot;padding: 20px; margin: 0 auto !important; background-color: #ffffff; border: 1px solid #f0f0f0; display: block !important; max-width: 600px !important; clear: both !important;&quot;&gt;
        ///            &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_ChangeEmailConfirmEmail_cshtml {
            get {
                return ResourceManager.GetString("Template_ChangeEmailConfirmEmail_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///@{
        ///    Layout = &quot;Template_EmailLayout_cshtml&quot;;
        ///    var ActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate?Email=&quot; + Model.UserName + &quot;&amp;Code=&quot; + Model.ActivationCode;
        ///}
        ///&lt;table style=&quot;padding: 20px; width: 100%;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td /&gt;
        ///        &lt;td style=&quot;padding: 20px; margin: 0 auto !important; background-color: #ffffff; border: 1px solid #f0f0f0; display: block !important; max-width: 600px !important; clear: both !important;&quot;&gt;
        ///            &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_ChangeEmailExistEmail_cshtml {
            get {
                return ResourceManager.GetString("Template_ChangeEmailExistEmail_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using AxCrypt.MVC
        ///@model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; style=&quot;font-family: &apos;Open sans&apos;, &apos;Helvetica Neue&apos;, Helvetica, Arial, sans-serif; line-height: 1.6;&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;link href=&quot;https://fonts. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_EmailLayout_cshtml {
            get {
                return ResourceManager.GetString("Template_EmailLayout_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///@{
        ///    Layout = &quot;Template_EmailLayout_cshtml&quot;;
        ///    var ActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate?Email=&quot; + Model.UserName + &quot;&amp;Code=&quot; + Model.ActivationCode;
        ///    var ManualActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate&quot;;
        ///    var DownloadLink = Model.ContentRootUrl + &quot;Download/&quot;;
        ///}
        ///&lt;table style=&quot;padding: 20px; width: 100%;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td /&gt;
        ///        &lt;td style=&quot;padding: 20px; margin: 0 auto !important; background-color [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_InvitationEmail_cshtml {
            get {
                return ResourceManager.GetString("Template_InvitationEmail_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///@{
        ///    Layout = null;
        ///    var ActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate?Email=&quot; + Model.UserName + &quot;&amp;Code=&quot; + Model.ActivationCode;
        ///    var ManualActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate&quot;;
        ///    var DownloadLink = Model.ContentRootUrl + &quot;Download/&quot;;
        ///}
        ///Hello and Welcome to AxCrypt,
        ///
        ///You have been invited to AxCrypt File Security by @Model.InvitedBy .
        ///
        ///To start securing your files just download and install AxCrypt from  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_InvitationEmailPlainText_cshtml {
            get {
                return ResourceManager.GetString("Template_InvitationEmailPlainText_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///@{
        ///    Layout = &quot;Template_EmailLayout_cshtml&quot;;
        ///    var ActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate?Email=&quot; + Model.UserName + &quot;&amp;Code=&quot; + Model.ActivationCode;
        ///}
        ///&lt;table style=&quot;padding: 20px; width: 100%;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td /&gt;
        ///        &lt;td style=&quot;padding: 20px; margin: 0 auto !important; background-color: #ffffff; border: 1px solid #f0f0f0; display: block !important; max-width: 600px !important; clear: both !important;&quot;&gt;
        ///            &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_PasswordResetEmail_cshtml {
            get {
                return ResourceManager.GetString("Template_PasswordResetEmail_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///@{
        ///    Layout = &quot;Template_EmailLayout_cshtml&quot;;
        ///    var ActivationLink = Model.RuntimeAppRootUrl + &quot;Home/Activate?Email=&quot; + Model.UserName + &quot;&amp;Code=&quot; + Model.ActivationCode;
        ///}
        ///&lt;table style=&quot;padding: 20px; width: 100%;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td /&gt;
        ///        &lt;td style=&quot;padding: 20px; margin: 0 auto !important; background-color: #ffffff; border: 1px solid #f0f0f0; display: block !important; max-width: 600px !important; clear: both !important;&quot;&gt;
        ///            &lt;d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Template_UnregisterEmail_cshtml {
            get {
                return ResourceManager.GetString("Template_UnregisterEmail_cshtml", resourceCulture);
            }
        }
    }
}
