//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxCrypt.Content.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxCrypt.Content.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status &apos;Aborted&apos; with &apos;{0}&apos;..
        /// </summary>
        public static string AbortedFileStatus {
            get {
                return ResourceManager.GetString("AbortedFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string AccountLoggedOnStatusText {
            get {
                return ResourceManager.GetString("AccountLoggedOnStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click decrypts and opens the document.
        /// </summary>
        public static string ActiveFileKnownKeyToolTip {
            get {
                return ResourceManager.GetString("ActiveFileKnownKeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click opens a Password-dialog before decrypting and opening the document..
        /// </summary>
        public static string ActiveFileToolTip {
            get {
                return ResourceManager.GetString("ActiveFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Document Encryption by Axantum Software AB
        ///
        ///Includes software from http://www.bouncycastle.org/ ..
        /// </summary>
        public static string AxCryptAboutDescription {
            get {
                return ResourceManager.GetString("AxCryptAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxCrypt Document Encryption.
        /// </summary>
        public static string AxCryptFileEncryption {
            get {
                return ResourceManager.GetString("AxCryptFileEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email address.
        /// </summary>
        public static string BadEmail {
            get {
                return ResourceManager.GetString("BadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled &apos;{0}&apos;..
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start application for &apos;{0}&apos;..
        /// </summary>
        public static string CannotStartApplication {
            get {
                return ResourceManager.GetString("CannotStartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write &apos;{0}&apos;..
        /// </summary>
        public static string CannotWrite {
            get {
                return ResourceManager.GetString("CannotWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassphraseDialogTitle {
            get {
                return ResourceManager.GetString("ChangePassphraseDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clean Decrypted.
        /// </summary>
        public static string CleanDecryptedToolStripMenuItemText {
            get {
                return ResourceManager.GetString("CleanDecryptedToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is decrypted, and may need to be cleaned. Close any open applications, and click the Clean Up button..
        /// </summary>
        public static string CleanUpNeededToolTip {
            get {
                return ResourceManager.GetString("CleanUpNeededToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to check for a newer version..
        /// </summary>
        public static string ClickToCheckForNewerVersionTooltip {
            get {
                return ResourceManager.GetString("ClickToCheckForNewerVersionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to clean and remove any open decrypted files, but ensure they are not in use first..
        /// </summary>
        public static string CloseAndRemoveOpenFilesToolStripButtonToolTipText {
            get {
                return ResourceManager.GetString("CloseAndRemoveOpenFilesToolStripButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;Account.
        /// </summary>
        public static string CreateAccountToolStripMenuItemText {
            get {
                return ResourceManager.GetString("CreateAccountToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account with a Secret and Sharing Key Pair so you can share encrypted files with others..
        /// </summary>
        public static string CreateAccountToolStripMenuItemToolTipText {
            get {
                return ResourceManager.GetString("CreateAccountToolStripMenuItemToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string CryptoNameText {
            get {
                return ResourceManager.GetString("CryptoNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Days.
        /// </summary>
        public static string DaysLeftPluralWarningPattern {
            get {
                return ResourceManager.GetString("DaysLeftPluralWarningPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Days.
        /// </summary>
        public static string DaysLeftPremiumLabelText {
            get {
                return ResourceManager.GetString("DaysLeftPremiumLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1 Day.
        /// </summary>
        public static string DaysLeftSingularWarningPattern {
            get {
                return ResourceManager.GetString("DaysLeftSingularWarningPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Premium subscription is about to expire. Click to renew..
        /// </summary>
        public static string DaysLeftWarningToolTip {
            get {
                return ResourceManager.GetString("DaysLeftWarningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Check Version Now.
        /// </summary>
        public static string DebugCheckVersionNowToolStripMenuItemText {
            get {
                return ResourceManager.GetString("DebugCheckVersionNowToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License &amp;Policy.
        /// </summary>
        public static string DebugCryptoPolicyToolStripMenuItemText {
            get {
                return ResourceManager.GetString("DebugCryptoPolicyToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Logging.
        /// </summary>
        public static string DebugLoggingToolStripMenuItemText {
            get {
                return ResourceManager.GetString("DebugLoggingToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manage Account.
        /// </summary>
        public static string DebugManageAccountToolStripMenuItemText {
            get {
                return ResourceManager.GetString("DebugManageAccountToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        public static string DebugOptionsToolStripMenuItemText {
            get {
                return ResourceManager.GetString("DebugOptionsToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Debug.
        /// </summary>
        public static string DebugToolStripMenuItemText {
            get {
                return ResourceManager.GetString("DebugToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decrypt and remove from list.
        /// </summary>
        public static string DecryptAndRemoveFromListToolStripMenuItemText {
            get {
                return ResourceManager.GetString("DecryptAndRemoveFromListToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string DecryptedFileColumnHeaderText {
            get {
                return ResourceManager.GetString("DecryptedFileColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumed open. Try to Close the application, or use the Clean function to remove it.
        /// </summary>
        public static string DecryptedFileToolTip {
            get {
                return ResourceManager.GetString("DecryptedFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents (*{0})|*{0}|All files (*.*)|*.*.
        /// </summary>
        public static string DecryptedSaveAsFileDialogFilterPattern {
            get {
                return ResourceManager.GetString("DecryptedSaveAsFileDialogFilterPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document exists, choose a new name to save as.
        /// </summary>
        public static string DecryptedSaveAsFileDialogTitle {
            get {
                return ResourceManager.GetString("DecryptedSaveAsFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has not been entered yet. Double-click to enter password and Open, or right-click for options.
        /// </summary>
        public static string DecryptedUnknownKeyFileToolTip {
            get {
                return ResourceManager.GetString("DecryptedUnknownKeyFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select document to decrypt.
        /// </summary>
        public static string DecryptFileOpenDialogTitle {
            get {
                return ResourceManager.GetString("DecryptFileOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decrypt.
        /// </summary>
        public static string DecryptToolStripMenuItemText {
            get {
                return ResourceManager.GetString("DecryptToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are Signed In. Click to Sign Out..
        /// </summary>
        public static string DefaultEncryptionKeyIsIsetToolTip {
            get {
                return ResourceManager.GetString("DefaultEncryptionKeyIsIsetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to open. If required you will be prompted for a password..
        /// </summary>
        public static string DoubleClickToOpenToolTip {
            get {
                return ResourceManager.GetString("DoubleClickToOpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxCrypt Documents (*{0})|*{0}|All files (*.*)|*.*.
        /// </summary>
        public static string EncryptedFileDialogFilterPattern {
            get {
                return ResourceManager.GetString("EncryptedFileDialogFilterPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted &amp;Folders.
        /// </summary>
        public static string EncryptedFoldersToolStripMenuItemText {
            get {
                return ResourceManager.GetString("EncryptedFoldersToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string EncryptedPathColumnHeaderText {
            get {
                return ResourceManager.GetString("EncryptedPathColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Document.
        /// </summary>
        public static string EncryptedSourceColumnHeader {
            get {
                return ResourceManager.GetString("EncryptedSourceColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select documents to encrypt.
        /// </summary>
        public static string EncryptFileOpenDialogTitle {
            get {
                return ResourceManager.GetString("EncryptFileOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Exists, Save As.
        /// </summary>
        public static string EncryptFileSaveAsDialogTitle {
            get {
                return ResourceManager.GetString("EncryptFileSaveAsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select documents to encrypt.
        /// </summary>
        public static string EncryptToolStripButtonToolTipText {
            get {
                return ResourceManager.GetString("EncryptToolStripButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Encrypt.
        /// </summary>
        public static string EncryptToolStripMenuItemText {
            get {
                return ResourceManager.GetString("EncryptToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;English.
        /// </summary>
        public static string EnglishLanguageToolStripMenuItemText {
            get {
                return ResourceManager.GetString("EnglishLanguageToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity &apos;{0}&apos; password.
        /// </summary>
        public static string EnterPassphraseForIdentityPrompt {
            get {
                return ResourceManager.GetString("EnterPassphraseForIdentityPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during processing of &apos;{0}&apos;..
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string ExitToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Account &amp;Secret and Sharing Key Pair.
        /// </summary>
        public static string ExportMyPrivateKeyToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ExportMyPrivateKeyToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To move an account, export the Secret and Sharing Key Pair and then import it elsewhere..
        /// </summary>
        public static string ExportMyPrivateKeyToolStripMenuItemToolTipText {
            get {
                return ResourceManager.GetString("ExportMyPrivateKeyToolStripMenuItemToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xport My Public Sharing Key.
        /// </summary>
        public static string ExportSharingKeyToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ExportSharingKeyToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the exported Public Sharing Key to others you want to be able to share encrypted files with you..
        /// </summary>
        public static string ExportSharingKeyToolStripMenuItemToolTipText {
            get {
                return ResourceManager.GetString("ExportSharingKeyToolStripMenuItemToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed. Probably not a valid Account Secret and Sharing Key Pair File..
        /// </summary>
        public static string FailedPrivateImport {
            get {
                return ResourceManager.GetString("FailedPrivateImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to us! Feedback or bug reports welcome..
        /// </summary>
        public static string FeedbackButtonText {
            get {
                return ResourceManager.GetString("FeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is already encrypted..
        /// </summary>
        public static string FileAlreadyEncrypted {
            get {
                return ResourceManager.GetString("FileAlreadyEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is already encrypted..
        /// </summary>
        public static string FileAlreadyEncryptedStatus {
            get {
                return ResourceManager.GetString("FileAlreadyEncryptedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos; already exists..
        /// </summary>
        public static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document &apos;{0}&apos; does not exist..
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is open in another application. Please close it and try again..
        /// </summary>
        public static string FileIsLockedWarning {
            get {
                return ResourceManager.GetString("FileIsLockedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed &apos;{0}&apos;..
        /// </summary>
        public static string FileOperationFailed {
            get {
                return ResourceManager.GetString("FileOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string FileToolStripMenuItemText {
            get {
                return ResourceManager.GetString("FileToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &apos;{0}&apos; already watched..
        /// </summary>
        public static string FolderAlreadyWatched {
            get {
                return ResourceManager.GetString("FolderAlreadyWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        public static string HelpAboutToolStripMenuItemText {
            get {
                return ResourceManager.GetString("HelpAboutToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string HelpToolStripMenuItemText {
            get {
                return ResourceManager.GetString("HelpToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View Help.
        /// </summary>
        public static string HelpViewHelpMenuItemText {
            get {
                return ResourceManager.GetString("HelpViewHelpMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &amp;Account Secret and Sharing Key Pair.
        /// </summary>
        public static string ImportMyPrivateKeyToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ImportMyPrivateKeyToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To move an account, export the Secret and Sharing Key Pair and then import it here..
        /// </summary>
        public static string ImportMyPrivateKeyToolStripMenuItemToolTipText {
            get {
                return ResourceManager.GetString("ImportMyPrivateKeyToolStripMenuItemToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import Someone&apos;s Public Sharing Key.
        /// </summary>
        public static string ImportOthersSharingKeyToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ImportOthersSharingKeyToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask your contact to export and send his/her Public Sharing Key to you and import it here. Then you can share encrypted files..
        /// </summary>
        public static string ImportOthersSharingKeyToolStripMenuItemToolTipText {
            get {
                return ResourceManager.GetString("ImportOthersSharingKeyToolStripMenuItemToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.axx)|*.axx|All Files (*.*)|*.*.
        /// </summary>
        public static string ImportPrivateKeysFileFilter {
            get {
                return ResourceManager.GetString("ImportPrivateKeysFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Account Secret and Sharing Key Pair File.
        /// </summary>
        public static string ImportPrivateKeysFileSelectionTitle {
            get {
                return ResourceManager.GetString("ImportPrivateKeysFileSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt|All Files (*.*)|*.*.
        /// </summary>
        public static string ImportPublicKeysFileFilter {
            get {
                return ResourceManager.GetString("ImportPublicKeysFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sharing Key Files.
        /// </summary>
        public static string ImportPublicKeysFileSelectionTitle {
            get {
                return ResourceManager.GetString("ImportPublicKeysFileSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent state with &apos;{0}&apos;..
        /// </summary>
        public static string InconsistentState {
            get {
                return ResourceManager.GetString("InconsistentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify time as &apos;hh:mm:ss.mmm&apos;..
        /// </summary>
        public static string Invalid_TimeSpan {
            get {
                return ResourceManager.GetString("Invalid_TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL..
        /// </summary>
        public static string Invalid_URL {
            get {
                return ResourceManager.GetString("Invalid_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format for an email address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key for &apos;{0}&apos;..
        /// </summary>
        public static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file or path &apos;{0}&apos; is invalid for this..
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Key Management.
        /// </summary>
        public static string KeyManagementToolStripMenuItemText {
            get {
                return ResourceManager.GetString("KeyManagementToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select documents to decrypt.
        /// </summary>
        public static string KeyShareToolStripButtonToolTipText {
            get {
                return ResourceManager.GetString("KeyShareToolStripButtonToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file key is shared with other AxCrypt users..
        /// </summary>
        public static string KeySharingExistsToolTip {
            get {
                return ResourceManager.GetString("KeySharingExistsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New contacts can only be added when online!.
        /// </summary>
        public static string KeySharingOffline {
            get {
                return ResourceManager.GetString("KeySharingOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to select encrypted files to share keys with others..
        /// </summary>
        public static string KeySharingToolTip {
            get {
                return ResourceManager.GetString("KeySharingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxCrypt must be restarted in order for the language change to take effect..
        /// </summary>
        public static string LanguageChangeRestartPrompt {
            get {
                return ResourceManager.GetString("LanguageChangeRestartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string LastAccessTimeColumnHeaderText {
            get {
                return ResourceManager.GetString("LastAccessTimeColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://account.axcrypt.net/Home/Purchase?email={0}.
        /// </summary>
        public static string LinkToAxCryptPremiumPurchasePage {
            get {
                return ResourceManager.GetString("LinkToAxCryptPremiumPurchasePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.axcrypt.net/documentation/get-started/.
        /// </summary>
        public static string LinkToGettingStarted {
            get {
                return ResourceManager.GetString("LinkToGettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed Out.
        /// </summary>
        public static string LoggedOffStatusText {
            get {
                return ResourceManager.GetString("LoggedOffStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string LoggedOnStatusText {
            get {
                return ResourceManager.GetString("LoggedOnStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string LogOffText {
            get {
                return ResourceManager.GetString("LogOffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This AxCrypt Identity already exists.
        /// </summary>
        public static string LogOnExists {
            get {
                return ResourceManager.GetString("LogOnExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LogOnText {
            get {
                return ResourceManager.GetString("LogOnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to Premium to enable the strongest encryption..
        /// </summary>
        public static string LowEncryptionWorkingToolTip {
            get {
                return ResourceManager.GetString("LowEncryptionWorkingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My AxCrypt.
        /// </summary>
        public static string MyAxCryptFolderName {
            get {
                return ResourceManager.GetString("MyAxCryptFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Password.
        /// </summary>
        public static string NewPassphraseDialogTitle {
            get {
                return ResourceManager.GetString("NewPassphraseDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is available! Click to download..
        /// </summary>
        public static string NewVersionIsAvailableTooltip {
            get {
                return ResourceManager.GetString("NewVersionIsAvailableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are Signed Out. Click to Sign In..
        /// </summary>
        public static string NoDefaultEncryptionKeySetToolTip {
            get {
                return ResourceManager.GetString("NoDefaultEncryptionKeySetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to check for updates..
        /// </summary>
        public static string NoNeedToCheckForUpdatesTooltip {
            get {
                return ResourceManager.GetString("NoNeedToCheckForUpdatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take a few minutes. Please be patient..
        /// </summary>
        public static string OfflineAccountBePatient {
            get {
                return ResourceManager.GetString("OfflineAccountBePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxCrypt Offline Account Creation..
        /// </summary>
        public static string OfflineAccountTitle {
            get {
                return ResourceManager.GetString("OfflineAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is old. Please click to check for a newer version..
        /// </summary>
        public static string OldVersionTooltip {
            get {
                return ResourceManager.GetString("OldVersionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select encrypted document to open.
        /// </summary>
        public static string OpenEncryptedFileOpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenEncryptedFileOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Encrypted.
        /// </summary>
        public static string OpenEncryptedToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OpenEncryptedToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string OpenFileColumnHeader {
            get {
                return ResourceManager.GetString("OpenFileColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change &amp;Password.
        /// </summary>
        public static string OptionsChangePassphraseToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OptionsChangePassphraseToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear All Settings and Exit.
        /// </summary>
        public static string OptionsClearAllSettingsAndExitToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OptionsClearAllSettingsAndExitToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Debug.
        /// </summary>
        public static string OptionsDebugToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OptionsDebugToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language.
        /// </summary>
        public static string OptionsLanguageToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OptionsLanguageToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&amp;ptions.
        /// </summary>
        public static string OptionsToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OptionsToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string PassphrasePrompt {
            get {
                return ResourceManager.GetString("PassphrasePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PassphraseVerificationMismatch {
            get {
                return ResourceManager.GetString("PassphraseVerificationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 10 characters..
        /// </summary>
        public static string PasswordPolicyViolation {
            get {
                return ResourceManager.GetString("PasswordPolicyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires a purchase of Premium!.
        /// </summary>
        public static string PremiumFeatureToolTipText {
            get {
                return ResourceManager.GetString("PremiumFeatureToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key sharing requires premimum. Click to upgrade now!.
        /// </summary>
        public static string PremiumNeededForKeyShare {
            get {
                return ResourceManager.GetString("PremiumNeededForKeyShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ProgressContextCancelToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ProgressContextCancelToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging Active Files.
        /// </summary>
        public static string PurgingActiveFiles {
            get {
                return ResourceManager.GetString("PurgingActiveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        public static string RecentFilesOpenToolStripMenuItemText {
            get {
                return ResourceManager.GetString("RecentFilesOpenToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string RecentFilesTabPageText {
            get {
                return ResourceManager.GetString("RecentFilesTabPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove from list without decrypting document.
        /// </summary>
        public static string RemoveRecentFileToolStripMenuItemText {
            get {
                return ResourceManager.GetString("RemoveRecentFileToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolStrip1.
        /// </summary>
        public static string RightToolStripText {
            get {
                return ResourceManager.GetString("RightToolStripText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Secure Delete.
        /// </summary>
        public static string SecureDeleteToolStripMenuItemText {
            get {
                return ResourceManager.GetString("SecureDeleteToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New AxCrypt User.
        /// </summary>
        public static string SharedWithUnverfiedMessageTitle {
            get {
                return ResourceManager.GetString("SharedWithUnverfiedMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to share securely with someone who has received but not yet responded to an invitation to use AxCrypt.
        ///
        ///Please consider informing &apos;{0}&apos; directly about AxCrypt file security..
        /// </summary>
        public static string SharedWithUnverifiedMessagePattern {
            get {
                return ResourceManager.GetString("SharedWithUnverifiedMessagePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Share Keys.
        /// </summary>
        public static string ShareKeysToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ShareKeysToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Svenska.
        /// </summary>
        public static string SwedishLanguageToolStripMenuItemText {
            get {
                return ResourceManager.GetString("SwedishLanguageToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using AxCrypt.MVC
        ///@model AxCrypt.MVC.ViewModels.UserEmailViewModel
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; style=&quot;margin: 0; padding: 0; font-family: &apos;Open sans&apos;, &apos;Helvetica Neue&apos;, Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6;&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=U [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Template_EmailLayout_cshtml {
            get {
                return ResourceManager.GetString("Template_EmailLayout_cshtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to restore the AxCrypt application window..
        /// </summary>
        public static string TrayBalloonTooltip {
            get {
                return ResourceManager.GetString("TrayBalloonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Try Broken File.
        /// </summary>
        public static string TryBrokenFileToolStripMenuItemText {
            get {
                return ResourceManager.GetString("TryBrokenFileToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownCrypto {
            get {
                return ResourceManager.GetString("UnknownCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status &apos;Unknown&apos; with &apos;{0}&apos;..
        /// </summary>
        public static string UnknownFileStatus {
            get {
                return ResourceManager.GetString("UnknownFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not previously known. Click &apos;New&apos; to create a new..
        /// </summary>
        public static string UnkownLogOn {
            get {
                return ResourceManager.GetString("UnkownLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} for &apos;{0}&apos;..
        /// </summary>
        public static string UnrecognizedError {
            get {
                return ResourceManager.GetString("UnrecognizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolStripButton1.
        /// </summary>
        public static string UpdateStatusButtonText {
            get {
                return ResourceManager.GetString("UpdateStatusButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Status.
        /// </summary>
        public static string UpdatingStatus {
            get {
                return ResourceManager.GetString("UpdatingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have updated AxCrypt. Unfortunately, your configuration must be reset. After restarting, your preferences and settings will unfortunately be lost. We apologize for the inconvenience. Your encrypted files are still safe and ok..
        /// </summary>
        public static string UserSettingsFormatChangeNeedsReset {
            get {
                return ResourceManager.GetString("UserSettingsFormatChangeNeedsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string WatchedFolderColumnHeaderText {
            get {
                return ResourceManager.GetString("WatchedFolderColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt &amp;Temporarily.
        /// </summary>
        public static string WatchedFoldersdecryptTemporarilyMenuItemText {
            get {
                return ResourceManager.GetString("WatchedFoldersdecryptTemporarilyMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &amp;Explorer Here.
        /// </summary>
        public static string WatchedFoldersOpenExplorerHereMenuItemText {
            get {
                return ResourceManager.GetString("WatchedFoldersOpenExplorerHereMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decrypt Permanently.
        /// </summary>
        public static string WatchedFoldersRemoveMenuItemText {
            get {
                return ResourceManager.GetString("WatchedFoldersRemoveMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Folders.
        /// </summary>
        public static string WatchedFoldersTabPageText {
            get {
                return ResourceManager.GetString("WatchedFoldersTabPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to AxCrypt!
        ///
        ///Using AxCrypt is really easy. Start with the main window, or use double-click and right-click in Windows Explorer for fully integrated use.
        ///
        ///To encrypt your first files, click the + icon in the toolbar and select them.
        ///
        ///For more information, click OK to open a web browser to our web site..
        /// </summary>
        public static string WelcomeToAxCrypt {
            get {
                return ResourceManager.GetString("WelcomeToAxCrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started with AxCrypt.
        /// </summary>
        public static string WelcomeToAxCryptTitle {
            get {
                return ResourceManager.GetString("WelcomeToAxCryptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select documents to securely delete.
        /// </summary>
        public static string WipeFileSelectFileDialogTitle {
            get {
                return ResourceManager.GetString("WipeFileSelectFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status &apos;Working&apos; with &apos;{0}&apos;..
        /// </summary>
        public static string WorkingFileStatus {
            get {
                return ResourceManager.GetString("WorkingFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password. Please try again..
        /// </summary>
        public static string WrongPassphrase {
            get {
                return ResourceManager.GetString("WrongPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong activation code. Please re-check you email..
        /// </summary>
        public static string WrongVerificationCode {
            get {
                return ResourceManager.GetString("WrongVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verfication code must be exactly 6 digits..
        /// </summary>
        public static string WrongVerificationCodeFormat {
            get {
                return ResourceManager.GetString("WrongVerificationCodeFormat", resourceCulture);
            }
        }
    }
}
