// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AxCrypt.Content {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AxCrypt.Content.Resources_fr", typeof(Resources_fr).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AbortedFileStatus {
            get {
                return ResourceManager.GetString("AbortedFileStatus", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string AccountLoggedOnStatusText {
            get {
                return ResourceManager.GetString("AccountLoggedOnStatusText", resourceCulture);
            }
        }
        
        internal static string AccountStatusLight {
            get {
                return ResourceManager.GetString("AccountStatusLight", resourceCulture);
            }
        }
        
        internal static string AccountStatusPremium {
            get {
                return ResourceManager.GetString("AccountStatusPremium", resourceCulture);
            }
        }
        
        internal static string AccountStatusPremiumIndefinate {
            get {
                return ResourceManager.GetString("AccountStatusPremiumIndefinate", resourceCulture);
            }
        }
        
        internal static string AccountStatusPremiumTrial {
            get {
                return ResourceManager.GetString("AccountStatusPremiumTrial", resourceCulture);
            }
        }
        
        internal static string ActivateErrorEmailOrCode {
            get {
                return ResourceManager.GetString("ActivateErrorEmailOrCode", resourceCulture);
            }
        }
        
        internal static string ActivateErrorNoRequest {
            get {
                return ResourceManager.GetString("ActivateErrorNoRequest", resourceCulture);
            }
        }
        
        internal static string ActivateErrorPassword {
            get {
                return ResourceManager.GetString("ActivateErrorPassword", resourceCulture);
            }
        }
        
        internal static string ActivateMailBodyButton {
            get {
                return ResourceManager.GetString("ActivateMailBodyButton", resourceCulture);
            }
        }
        
        internal static string ActivateMailBodyCode {
            get {
                return ResourceManager.GetString("ActivateMailBodyCode", resourceCulture);
            }
        }
        
        internal static string ActivateMailBodyCodePlainText {
            get {
                return ResourceManager.GetString("ActivateMailBodyCodePlainText", resourceCulture);
            }
        }
        
        internal static string ActivateMailBodyFreeTrial {
            get {
                return ResourceManager.GetString("ActivateMailBodyFreeTrial", resourceCulture);
            }
        }
        
        internal static string ActivateMailBodyFreeTrialPlainText {
            get {
                return ResourceManager.GetString("ActivateMailBodyFreeTrialPlainText", resourceCulture);
            }
        }
        
        internal static string ActivateMailBodyIntro {
            get {
                return ResourceManager.GetString("ActivateMailBodyIntro", resourceCulture);
            }
        }
        
        internal static string ActivateMailBodyManualLink {
            get {
                return ResourceManager.GetString("ActivateMailBodyManualLink", resourceCulture);
            }
        }
        
        internal static string ActivateMailBodyManualLinkPlainText {
            get {
                return ResourceManager.GetString("ActivateMailBodyManualLinkPlainText", resourceCulture);
            }
        }
        
        internal static string ActivateMailBodyTitle {
            get {
                return ResourceManager.GetString("ActivateMailBodyTitle", resourceCulture);
            }
        }
        
        internal static string ActivateMailSubject {
            get {
                return ResourceManager.GetString("ActivateMailSubject", resourceCulture);
            }
        }
        
        internal static string ActivateManuallyPageBody {
            get {
                return ResourceManager.GetString("ActivateManuallyPageBody", resourceCulture);
            }
        }
        
        internal static string ActivatePageBody {
            get {
                return ResourceManager.GetString("ActivatePageBody", resourceCulture);
            }
        }
        
        internal static string ActivatePageTitle {
            get {
                return ResourceManager.GetString("ActivatePageTitle", resourceCulture);
            }
        }
        
        internal static string ActivateSuccess {
            get {
                return ResourceManager.GetString("ActivateSuccess", resourceCulture);
            }
        }
        
        internal static string ActiveFileKnownKeyToolTip {
            get {
                return ResourceManager.GetString("ActiveFileKnownKeyToolTip", resourceCulture);
            }
        }
        
        internal static string ActiveFileToolTip {
            get {
                return ResourceManager.GetString("ActiveFileToolTip", resourceCulture);
            }
        }
        
        internal static string AddSecureFolderMenuItemText {
            get {
                return ResourceManager.GetString("AddSecureFolderMenuItemText", resourceCulture);
            }
        }
        
        internal static string AddSecureFolderTitle {
            get {
                return ResourceManager.GetString("AddSecureFolderTitle", resourceCulture);
            }
        }
        
        internal static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        internal static string AutoDeletionMailSubject {
            get {
                return ResourceManager.GetString("AutoDeletionMailSubject", resourceCulture);
            }
        }
        
        internal static string AxCryptAboutDescription {
            get {
                return ResourceManager.GetString("AxCryptAboutDescription", resourceCulture);
            }
        }
        
        internal static string AxCryptFileEncryption {
            get {
                return ResourceManager.GetString("AxCryptFileEncryption", resourceCulture);
            }
        }
        
        internal static string BadEmail {
            get {
                return ResourceManager.GetString("BadEmail", resourceCulture);
            }
        }
        
        internal static string ButtonActivateText {
            get {
                return ResourceManager.GetString("ButtonActivateText", resourceCulture);
            }
        }
        
        internal static string ButtonCancelAllText {
            get {
                return ResourceManager.GetString("ButtonCancelAllText", resourceCulture);
            }
        }
        
        internal static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        internal static string ButtonChangePasswordText {
            get {
                return ResourceManager.GetString("ButtonChangePasswordText", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteAxCryptIdText {
            get {
                return ResourceManager.GetString("ButtonDeleteAxCryptIdText", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteText {
            get {
                return ResourceManager.GetString("ButtonDeleteText", resourceCulture);
            }
        }
        
        internal static string ButtonEditText {
            get {
                return ResourceManager.GetString("ButtonEditText", resourceCulture);
            }
        }
        
        internal static string ButtonEllipsisText {
            get {
                return ResourceManager.GetString("ButtonEllipsisText", resourceCulture);
            }
        }
        
        internal static string ButtonExitText {
            get {
                return ResourceManager.GetString("ButtonExitText", resourceCulture);
            }
        }
        
        internal static string ButtonHelpText {
            get {
                return ResourceManager.GetString("ButtonHelpText", resourceCulture);
            }
        }
        
        internal static string ButtonNewText {
            get {
                return ResourceManager.GetString("ButtonNewText", resourceCulture);
            }
        }
        
        internal static string ButtonNoText {
            get {
                return ResourceManager.GetString("ButtonNoText", resourceCulture);
            }
        }
        
        internal static string ButtonOkText {
            get {
                return ResourceManager.GetString("ButtonOkText", resourceCulture);
            }
        }
        
        internal static string ButtonSaveText {
            get {
                return ResourceManager.GetString("ButtonSaveText", resourceCulture);
            }
        }
        
        internal static string ButtonSendText {
            get {
                return ResourceManager.GetString("ButtonSendText", resourceCulture);
            }
        }
        
        internal static string ButtonShareRightText {
            get {
                return ResourceManager.GetString("ButtonShareRightText", resourceCulture);
            }
        }
        
        internal static string ButtonSignInBuyText {
            get {
                return ResourceManager.GetString("ButtonSignInBuyText", resourceCulture);
            }
        }
        
        internal static string ButtonSignInText {
            get {
                return ResourceManager.GetString("ButtonSignInText", resourceCulture);
            }
        }
        
        internal static string ButtonSignUpText {
            get {
                return ResourceManager.GetString("ButtonSignUpText", resourceCulture);
            }
        }
        
        internal static string ButtonSuggestText {
            get {
                return ResourceManager.GetString("ButtonSuggestText", resourceCulture);
            }
        }
        
        internal static string ButtonUnshareLeftText {
            get {
                return ResourceManager.GetString("ButtonUnshareLeftText", resourceCulture);
            }
        }
        
        internal static string ButtonYesText {
            get {
                return ResourceManager.GetString("ButtonYesText", resourceCulture);
            }
        }
        
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        internal static string CannotStartApplication {
            get {
                return ResourceManager.GetString("CannotStartApplication", resourceCulture);
            }
        }
        
        internal static string CannotWrite {
            get {
                return ResourceManager.GetString("CannotWrite", resourceCulture);
            }
        }
        
        internal static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        internal static string CaptchaLabel {
            get {
                return ResourceManager.GetString("CaptchaLabel", resourceCulture);
            }
        }
        
        internal static string ChangeEmailConfirmMailBody1 {
            get {
                return ResourceManager.GetString("ChangeEmailConfirmMailBody1", resourceCulture);
            }
        }
        
        internal static string ChangeEmailConfirmMailBody2 {
            get {
                return ResourceManager.GetString("ChangeEmailConfirmMailBody2", resourceCulture);
            }
        }
        
        internal static string ChangeEmailConfirmMailBodyButton {
            get {
                return ResourceManager.GetString("ChangeEmailConfirmMailBodyButton", resourceCulture);
            }
        }
        
        internal static string ChangeEmailConfirmMailSubject {
            get {
                return ResourceManager.GetString("ChangeEmailConfirmMailSubject", resourceCulture);
            }
        }
        
        internal static string ChangeEmailConfirmSuccess {
            get {
                return ResourceManager.GetString("ChangeEmailConfirmSuccess", resourceCulture);
            }
        }
        
        internal static string ChangeEmailExistMailBody1 {
            get {
                return ResourceManager.GetString("ChangeEmailExistMailBody1", resourceCulture);
            }
        }
        
        internal static string ChangeEmailExistMailBody2 {
            get {
                return ResourceManager.GetString("ChangeEmailExistMailBody2", resourceCulture);
            }
        }
        
        internal static string ChangeEmailExistMailBody3 {
            get {
                return ResourceManager.GetString("ChangeEmailExistMailBody3", resourceCulture);
            }
        }
        
        internal static string ChangeEmailExistMailSubject {
            get {
                return ResourceManager.GetString("ChangeEmailExistMailSubject", resourceCulture);
            }
        }
        
        internal static string ChangeEmailMarkError {
            get {
                return ResourceManager.GetString("ChangeEmailMarkError", resourceCulture);
            }
        }
        
        internal static string ChangeEmailMarkSuccess {
            get {
                return ResourceManager.GetString("ChangeEmailMarkSuccess", resourceCulture);
            }
        }
        
        internal static string ChangeNotificationSettingsSuccess {
            get {
                return ResourceManager.GetString("ChangeNotificationSettingsSuccess", resourceCulture);
            }
        }
        
        internal static string ChangePassphraseDialogTitle {
            get {
                return ResourceManager.GetString("ChangePassphraseDialogTitle", resourceCulture);
            }
        }
        
        internal static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        internal static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        internal static string CleanDecryptedToolStripMenuItemText {
            get {
                return ResourceManager.GetString("CleanDecryptedToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string CleanUpNeededToolTip {
            get {
                return ResourceManager.GetString("CleanUpNeededToolTip", resourceCulture);
            }
        }
        
        internal static string ClickToCheckForNewerVersionTooltip {
            get {
                return ResourceManager.GetString("ClickToCheckForNewerVersionTooltip", resourceCulture);
            }
        }
        
        internal static string CloseAndRemoveOpenFilesToolStripButtonToolTipText {
            get {
                return ResourceManager.GetString("CloseAndRemoveOpenFilesToolStripButtonToolTipText", resourceCulture);
            }
        }
        
        internal static string ColumnAmountPaidHeader {
            get {
                return ResourceManager.GetString("ColumnAmountPaidHeader", resourceCulture);
            }
        }
        
        internal static string ColumnExpiresHeader {
            get {
                return ResourceManager.GetString("ColumnExpiresHeader", resourceCulture);
            }
        }
        
        internal static string ColumnFolderHeader {
            get {
                return ResourceManager.GetString("ColumnFolderHeader", resourceCulture);
            }
        }
        
        internal static string ColumnProductHeader {
            get {
                return ResourceManager.GetString("ColumnProductHeader", resourceCulture);
            }
        }
        
        internal static string ColumnTimestampHeader {
            get {
                return ResourceManager.GetString("ColumnTimestampHeader", resourceCulture);
            }
        }
        
        internal static string ColumnTransactionDateHeader {
            get {
                return ResourceManager.GetString("ColumnTransactionDateHeader", resourceCulture);
            }
        }
        
        internal static string ConfirmAllCheckBoxText {
            get {
                return ResourceManager.GetString("ConfirmAllCheckBoxText", resourceCulture);
            }
        }
        
        internal static string ContactInfoPhone {
            get {
                return ResourceManager.GetString("ContactInfoPhone", resourceCulture);
            }
        }
        
        internal static string ContactInfoTitle {
            get {
                return ResourceManager.GetString("ContactInfoTitle", resourceCulture);
            }
        }
        
        internal static string CookiePolicyBlockedError {
            get {
                return ResourceManager.GetString("CookiePolicyBlockedError", resourceCulture);
            }
        }
        
        internal static string CookiePolicyPageBody {
            get {
                return ResourceManager.GetString("CookiePolicyPageBody", resourceCulture);
            }
        }
        
        internal static string CookiePolicyPageTitle {
            get {
                return ResourceManager.GetString("CookiePolicyPageTitle", resourceCulture);
            }
        }
        
        internal static string CookiesDisabledError {
            get {
                return ResourceManager.GetString("CookiesDisabledError", resourceCulture);
            }
        }
        
        internal static string CreateAccountToolStripMenuItemText {
            get {
                return ResourceManager.GetString("CreateAccountToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string CreateAccountToolStripMenuItemToolTipText {
            get {
                return ResourceManager.GetString("CreateAccountToolStripMenuItemToolTipText", resourceCulture);
            }
        }
        
        internal static string CryptoNameText {
            get {
                return ResourceManager.GetString("CryptoNameText", resourceCulture);
            }
        }
        
        internal static string DaysLeftPluralWarningPattern {
            get {
                return ResourceManager.GetString("DaysLeftPluralWarningPattern", resourceCulture);
            }
        }
        
        internal static string DaysLeftSingularWarningPattern {
            get {
                return ResourceManager.GetString("DaysLeftSingularWarningPattern", resourceCulture);
            }
        }
        
        internal static string DaysLeftWarningToolTip {
            get {
                return ResourceManager.GetString("DaysLeftWarningToolTip", resourceCulture);
            }
        }
        
        internal static string DecryptAndRemoveFromListToolStripMenuItemText {
            get {
                return ResourceManager.GetString("DecryptAndRemoveFromListToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string DecryptedFileColumnHeaderText {
            get {
                return ResourceManager.GetString("DecryptedFileColumnHeaderText", resourceCulture);
            }
        }
        
        internal static string DecryptedFileToolTip {
            get {
                return ResourceManager.GetString("DecryptedFileToolTip", resourceCulture);
            }
        }
        
        internal static string DecryptedSaveAsFileDialogFilterPattern {
            get {
                return ResourceManager.GetString("DecryptedSaveAsFileDialogFilterPattern", resourceCulture);
            }
        }
        
        internal static string DecryptedSaveAsFileDialogTitle {
            get {
                return ResourceManager.GetString("DecryptedSaveAsFileDialogTitle", resourceCulture);
            }
        }
        
        internal static string DecryptedUnknownKeyFileToolTip {
            get {
                return ResourceManager.GetString("DecryptedUnknownKeyFileToolTip", resourceCulture);
            }
        }
        
        internal static string DecryptFileOpenDialogTitle {
            get {
                return ResourceManager.GetString("DecryptFileOpenDialogTitle", resourceCulture);
            }
        }
        
        internal static string DecryptToolStripMenuItemText {
            get {
                return ResourceManager.GetString("DecryptToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string DefaultEncryptionKeyIsIsetToolTip {
            get {
                return ResourceManager.GetString("DefaultEncryptionKeyIsIsetToolTip", resourceCulture);
            }
        }
        
        internal static string DeleteAccountErrorIncorrectPassword {
            get {
                return ResourceManager.GetString("DeleteAccountErrorIncorrectPassword", resourceCulture);
            }
        }
        
        internal static string DeleteAccountSuccess {
            get {
                return ResourceManager.GetString("DeleteAccountSuccess", resourceCulture);
            }
        }
        
        internal static string DeleteSecretErrorNotFound {
            get {
                return ResourceManager.GetString("DeleteSecretErrorNotFound", resourceCulture);
            }
        }
        
        internal static string DeleteSecretSuccess {
            get {
                return ResourceManager.GetString("DeleteSecretSuccess", resourceCulture);
            }
        }
        
        internal static string DialogAxCryptIdEmailTitle {
            get {
                return ResourceManager.GetString("DialogAxCryptIdEmailTitle", resourceCulture);
            }
        }
        
        internal static string DialogAxCryptIdFirstTimeText {
            get {
                return ResourceManager.GetString("DialogAxCryptIdFirstTimeText", resourceCulture);
            }
        }
        
        internal static string DialogDecryptTitle {
            get {
                return ResourceManager.GetString("DialogDecryptTitle", resourceCulture);
            }
        }
        
        internal static string DialogExportAxCryptIdFileName {
            get {
                return ResourceManager.GetString("DialogExportAxCryptIdFileName", resourceCulture);
            }
        }
        
        internal static string DialogExportAxCryptIdFilter {
            get {
                return ResourceManager.GetString("DialogExportAxCryptIdFilter", resourceCulture);
            }
        }
        
        internal static string DialogExportAxCryptIdTitle {
            get {
                return ResourceManager.GetString("DialogExportAxCryptIdTitle", resourceCulture);
            }
        }
        
        internal static string DialogExportSharingKeyFileName {
            get {
                return ResourceManager.GetString("DialogExportSharingKeyFileName", resourceCulture);
            }
        }
        
        internal static string DialogExportSharingKeyFilter {
            get {
                return ResourceManager.GetString("DialogExportSharingKeyFilter", resourceCulture);
            }
        }
        
        internal static string DialogExportSharingKeyTitle {
            get {
                return ResourceManager.GetString("DialogExportSharingKeyTitle", resourceCulture);
            }
        }
        
        internal static string DialogFilePasswordTitle {
            get {
                return ResourceManager.GetString("DialogFilePasswordTitle", resourceCulture);
            }
        }
        
        internal static string DialogImportPrivateAxCryptIdAccessIdPrompt {
            get {
                return ResourceManager.GetString("DialogImportPrivateAxCryptIdAccessIdPrompt", resourceCulture);
            }
        }
        
        internal static string DialogImportPrivateAxCryptIdTitle {
            get {
                return ResourceManager.GetString("DialogImportPrivateAxCryptIdTitle", resourceCulture);
            }
        }
        
        internal static string DialogKeyShareTitle {
            get {
                return ResourceManager.GetString("DialogKeyShareTitle", resourceCulture);
            }
        }
        
        internal static string DialogManageAxcryptIdTitle {
            get {
                return ResourceManager.GetString("DialogManageAxcryptIdTitle", resourceCulture);
            }
        }
        
        internal static string DialogNewPasswordTitle {
            get {
                return ResourceManager.GetString("DialogNewPasswordTitle", resourceCulture);
            }
        }
        
        internal static string DialogVerifyAccountTitle {
            get {
                return ResourceManager.GetString("DialogVerifyAccountTitle", resourceCulture);
            }
        }
        
        internal static string DialogWatchedFoldersTitle {
            get {
                return ResourceManager.GetString("DialogWatchedFoldersTitle", resourceCulture);
            }
        }
        
        internal static string DoubleClickToOpenToolTip {
            get {
                return ResourceManager.GetString("DoubleClickToOpenToolTip", resourceCulture);
            }
        }
        
        internal static string EditSecretErrorIsReadOnly {
            get {
                return ResourceManager.GetString("EditSecretErrorIsReadOnly", resourceCulture);
            }
        }
        
        internal static string EditSecretErrorNotFound {
            get {
                return ResourceManager.GetString("EditSecretErrorNotFound", resourceCulture);
            }
        }
        
        internal static string EditSecretSuccess {
            get {
                return ResourceManager.GetString("EditSecretSuccess", resourceCulture);
            }
        }
        
        internal static string EmptySecretTruncatedDescriptionLinkText {
            get {
                return ResourceManager.GetString("EmptySecretTruncatedDescriptionLinkText", resourceCulture);
            }
        }
        
        internal static string EncryptedFileDialogFilterPattern {
            get {
                return ResourceManager.GetString("EncryptedFileDialogFilterPattern", resourceCulture);
            }
        }
        
        internal static string EncryptedFoldersToolStripMenuItemText {
            get {
                return ResourceManager.GetString("EncryptedFoldersToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string EncryptedPathColumnHeaderText {
            get {
                return ResourceManager.GetString("EncryptedPathColumnHeaderText", resourceCulture);
            }
        }
        
        internal static string EncryptedSourceColumnHeader {
            get {
                return ResourceManager.GetString("EncryptedSourceColumnHeader", resourceCulture);
            }
        }
        
        internal static string EncryptFileOpenDialogTitle {
            get {
                return ResourceManager.GetString("EncryptFileOpenDialogTitle", resourceCulture);
            }
        }
        
        internal static string EncryptFileSaveAsDialogTitle {
            get {
                return ResourceManager.GetString("EncryptFileSaveAsDialogTitle", resourceCulture);
            }
        }
        
        internal static string EncryptToolStripButtonToolTipText {
            get {
                return ResourceManager.GetString("EncryptToolStripButtonToolTipText", resourceCulture);
            }
        }
        
        internal static string EncryptToolStripMenuItemText {
            get {
                return ResourceManager.GetString("EncryptToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string EnterPassphraseForIdentityPrompt {
            get {
                return ResourceManager.GetString("EnterPassphraseForIdentityPrompt", resourceCulture);
            }
        }
        
        internal static string ErrorEmailMismatch {
            get {
                return ResourceManager.GetString("ErrorEmailMismatch", resourceCulture);
            }
        }
        
        internal static string ErrorPasswordMismatch {
            get {
                return ResourceManager.GetString("ErrorPasswordMismatch", resourceCulture);
            }
        }
        
        internal static string ErrorPasswordTooLong {
            get {
                return ResourceManager.GetString("ErrorPasswordTooLong", resourceCulture);
            }
        }
        
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        internal static string ExitToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string ExportMyPrivateKeyToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ExportMyPrivateKeyToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string ExportMyPrivateKeyToolStripMenuItemToolTipText {
            get {
                return ResourceManager.GetString("ExportMyPrivateKeyToolStripMenuItemToolTipText", resourceCulture);
            }
        }
        
        internal static string ExportSharingKeyToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ExportSharingKeyToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string ExportSharingKeyToolStripMenuItemToolTipText {
            get {
                return ResourceManager.GetString("ExportSharingKeyToolStripMenuItemToolTipText", resourceCulture);
            }
        }
        
        internal static string FailedPrivateImport {
            get {
                return ResourceManager.GetString("FailedPrivateImport", resourceCulture);
            }
        }
        
        internal static string FeedbackButtonText {
            get {
                return ResourceManager.GetString("FeedbackButtonText", resourceCulture);
            }
        }
        
        internal static string FileAlreadyEncrypted {
            get {
                return ResourceManager.GetString("FileAlreadyEncrypted", resourceCulture);
            }
        }
        
        internal static string FileAlreadyEncryptedStatus {
            get {
                return ResourceManager.GetString("FileAlreadyEncryptedStatus", resourceCulture);
            }
        }
        
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        internal static string FileIsLockedWarning {
            get {
                return ResourceManager.GetString("FileIsLockedWarning", resourceCulture);
            }
        }
        
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        internal static string FileOperationFailed {
            get {
                return ResourceManager.GetString("FileOperationFailed", resourceCulture);
            }
        }
        
        internal static string FileToolStripMenuItemText {
            get {
                return ResourceManager.GetString("FileToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string FolderAlreadyWatched {
            get {
                return ResourceManager.GetString("FolderAlreadyWatched", resourceCulture);
            }
        }
        
        internal static string FooterInfoBody {
            get {
                return ResourceManager.GetString("FooterInfoBody", resourceCulture);
            }
        }
        
        internal static string FooterInfoTitle {
            get {
                return ResourceManager.GetString("FooterInfoTitle", resourceCulture);
            }
        }
        
        internal static string GetLogErrorDateFormat {
            get {
                return ResourceManager.GetString("GetLogErrorDateFormat", resourceCulture);
            }
        }
        
        internal static string HelpAboutToolStripMenuItemText {
            get {
                return ResourceManager.GetString("HelpAboutToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string HelpToolStripMenuItemText {
            get {
                return ResourceManager.GetString("HelpToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string HelpViewHelpMenuItemText {
            get {
                return ResourceManager.GetString("HelpViewHelpMenuItemText", resourceCulture);
            }
        }
        
        internal static string ImportMyPrivateKeyToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ImportMyPrivateKeyToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string ImportMyPrivateKeyToolStripMenuItemToolTipText {
            get {
                return ResourceManager.GetString("ImportMyPrivateKeyToolStripMenuItemToolTipText", resourceCulture);
            }
        }
        
        internal static string ImportOthersSharingKeyToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ImportOthersSharingKeyToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string ImportOthersSharingKeyToolStripMenuItemToolTipText {
            get {
                return ResourceManager.GetString("ImportOthersSharingKeyToolStripMenuItemToolTipText", resourceCulture);
            }
        }
        
        internal static string ImportPrivateKeysFileFilter {
            get {
                return ResourceManager.GetString("ImportPrivateKeysFileFilter", resourceCulture);
            }
        }
        
        internal static string ImportPrivateKeysFileSelectionTitle {
            get {
                return ResourceManager.GetString("ImportPrivateKeysFileSelectionTitle", resourceCulture);
            }
        }
        
        internal static string ImportPublicKeysFileFilter {
            get {
                return ResourceManager.GetString("ImportPublicKeysFileFilter", resourceCulture);
            }
        }
        
        internal static string ImportPublicKeysFileSelectionTitle {
            get {
                return ResourceManager.GetString("ImportPublicKeysFileSelectionTitle", resourceCulture);
            }
        }
        
        internal static string IndexPageTitle {
            get {
                return ResourceManager.GetString("IndexPageTitle", resourceCulture);
            }
        }
        
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        internal static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        internal static string Invalid_TimeSpan {
            get {
                return ResourceManager.GetString("Invalid_TimeSpan", resourceCulture);
            }
        }
        
        internal static string Invalid_URL {
            get {
                return ResourceManager.GetString("Invalid_URL", resourceCulture);
            }
        }
        
        internal static string InvitationMailBodyIntro {
            get {
                return ResourceManager.GetString("InvitationMailBodyIntro", resourceCulture);
            }
        }
        
        internal static string InvitationMailBodyIntroPlainText {
            get {
                return ResourceManager.GetString("InvitationMailBodyIntroPlainText", resourceCulture);
            }
        }
        
        internal static string InvitationMailSubject {
            get {
                return ResourceManager.GetString("InvitationMailSubject", resourceCulture);
            }
        }
        
        internal static string JavaScriptDisabledError {
            get {
                return ResourceManager.GetString("JavaScriptDisabledError", resourceCulture);
            }
        }
        
        internal static string KeyFileBrowseFilter {
            get {
                return ResourceManager.GetString("KeyFileBrowseFilter", resourceCulture);
            }
        }
        
        internal static string KeyFileBrowseTitle {
            get {
                return ResourceManager.GetString("KeyFileBrowseTitle", resourceCulture);
            }
        }
        
        internal static string KeyFilePrompt {
            get {
                return ResourceManager.GetString("KeyFilePrompt", resourceCulture);
            }
        }
        
        internal static string KeyManagementToolStripMenuItemText {
            get {
                return ResourceManager.GetString("KeyManagementToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string KeyShareToolStripButtonToolTipText {
            get {
                return ResourceManager.GetString("KeyShareToolStripButtonToolTipText", resourceCulture);
            }
        }
        
        internal static string KeySharingExistsToolTip {
            get {
                return ResourceManager.GetString("KeySharingExistsToolTip", resourceCulture);
            }
        }
        
        internal static string KeySharingOffline {
            get {
                return ResourceManager.GetString("KeySharingOffline", resourceCulture);
            }
        }
        
        internal static string KeySharingToolTip {
            get {
                return ResourceManager.GetString("KeySharingToolTip", resourceCulture);
            }
        }
        
        internal static string LanguageChangeRestartPrompt {
            get {
                return ResourceManager.GetString("LanguageChangeRestartPrompt", resourceCulture);
            }
        }
        
        internal static string LastAccessTimeColumnHeaderText {
            get {
                return ResourceManager.GetString("LastAccessTimeColumnHeaderText", resourceCulture);
            }
        }
        
        internal static string LicenseFreeNameText {
            get {
                return ResourceManager.GetString("LicenseFreeNameText", resourceCulture);
            }
        }
        
        internal static string LicensePremiumNameText {
            get {
                return ResourceManager.GetString("LicensePremiumNameText", resourceCulture);
            }
        }
        
        internal static string LinkTextBackToMainSite {
            get {
                return ResourceManager.GetString("LinkTextBackToMainSite", resourceCulture);
            }
        }
        
        internal static string LoggedOffStatusText {
            get {
                return ResourceManager.GetString("LoggedOffStatusText", resourceCulture);
            }
        }
        
        internal static string LoggedOnStatusText {
            get {
                return ResourceManager.GetString("LoggedOnStatusText", resourceCulture);
            }
        }
        
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        internal static string LoginPurchaseError {
            get {
                return ResourceManager.GetString("LoginPurchaseError", resourceCulture);
            }
        }
        
        internal static string LogOffText {
            get {
                return ResourceManager.GetString("LogOffText", resourceCulture);
            }
        }
        
        internal static string LogOnText {
            get {
                return ResourceManager.GetString("LogOnText", resourceCulture);
            }
        }
        
        internal static string LowEncryptionWorkingToolTip {
            get {
                return ResourceManager.GetString("LowEncryptionWorkingToolTip", resourceCulture);
            }
        }
        
        internal static string MailBodyFooter {
            get {
                return ResourceManager.GetString("MailBodyFooter", resourceCulture);
            }
        }
        
        internal static string MailBodyFooterPlainText {
            get {
                return ResourceManager.GetString("MailBodyFooterPlainText", resourceCulture);
            }
        }
        
        internal static string MailBodyOutroHtml {
            get {
                return ResourceManager.GetString("MailBodyOutroHtml", resourceCulture);
            }
        }
        
        internal static string MailBodyPremiumFeaturesHtml {
            get {
                return ResourceManager.GetString("MailBodyPremiumFeaturesHtml", resourceCulture);
            }
        }
        
        internal static string MailBodySignature {
            get {
                return ResourceManager.GetString("MailBodySignature", resourceCulture);
            }
        }
        
        internal static string MailBodySignaturePlainText {
            get {
                return ResourceManager.GetString("MailBodySignaturePlainText", resourceCulture);
            }
        }
        
        internal static string MailBodyTitle {
            get {
                return ResourceManager.GetString("MailBodyTitle", resourceCulture);
            }
        }
        
        internal static string MailBodyTitleHtml {
            get {
                return ResourceManager.GetString("MailBodyTitleHtml", resourceCulture);
            }
        }
        
        internal static string MainSiteUrl {
            get {
                return ResourceManager.GetString("MainSiteUrl", resourceCulture);
            }
        }
        
        internal static string MenuAxCryptIdText {
            get {
                return ResourceManager.GetString("MenuAxCryptIdText", resourceCulture);
            }
        }
        
        internal static string MenuDecryptPermanentlyText {
            get {
                return ResourceManager.GetString("MenuDecryptPermanentlyText", resourceCulture);
            }
        }
        
        internal static string MenuDecryptTemporarilyText {
            get {
                return ResourceManager.GetString("MenuDecryptTemporarilyText", resourceCulture);
            }
        }
        
        internal static string MenuOpenExplorerHereText {
            get {
                return ResourceManager.GetString("MenuOpenExplorerHereText", resourceCulture);
            }
        }
        
        internal static string MessageInvalidSignUpEmailText {
            get {
                return ResourceManager.GetString("MessageInvalidSignUpEmailText", resourceCulture);
            }
        }
        
        internal static string MessageInvalidSignUpEmailTitle {
            get {
                return ResourceManager.GetString("MessageInvalidSignUpEmailTitle", resourceCulture);
            }
        }
        
        internal static string MessageServerUpdateText {
            get {
                return ResourceManager.GetString("MessageServerUpdateText", resourceCulture);
            }
        }
        
        internal static string MessageServerUpdateTitle {
            get {
                return ResourceManager.GetString("MessageServerUpdateTitle", resourceCulture);
            }
        }
        
        internal static string MessageSigningUpText {
            get {
                return ResourceManager.GetString("MessageSigningUpText", resourceCulture);
            }
        }
        
        internal static string MessageSigningUpTitle {
            get {
                return ResourceManager.GetString("MessageSigningUpTitle", resourceCulture);
            }
        }
        
        internal static string MessageSignUpInternetRequiredText {
            get {
                return ResourceManager.GetString("MessageSignUpInternetRequiredText", resourceCulture);
            }
        }
        
        internal static string MessageSignUpInternetRequiredTitle {
            get {
                return ResourceManager.GetString("MessageSignUpInternetRequiredTitle", resourceCulture);
            }
        }
        
        internal static string MessageSignUpUnexpectedErrorText {
            get {
                return ResourceManager.GetString("MessageSignUpUnexpectedErrorText", resourceCulture);
            }
        }
        
        internal static string MessageSignUpUnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("MessageSignUpUnexpectedErrorTitle", resourceCulture);
            }
        }
        
        internal static string MessageUnexpectedErrorText {
            get {
                return ResourceManager.GetString("MessageUnexpectedErrorText", resourceCulture);
            }
        }
        
        internal static string MessageUnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("MessageUnexpectedErrorTitle", resourceCulture);
            }
        }
        
        internal static string NewPassphraseDialogTitle {
            get {
                return ResourceManager.GetString("NewPassphraseDialogTitle", resourceCulture);
            }
        }
        
        internal static string NewSecretSuccess {
            get {
                return ResourceManager.GetString("NewSecretSuccess", resourceCulture);
            }
        }
        
        internal static string NewVersionIsAvailableTooltip {
            get {
                return ResourceManager.GetString("NewVersionIsAvailableTooltip", resourceCulture);
            }
        }
        
        internal static string NoButtonText {
            get {
                return ResourceManager.GetString("NoButtonText", resourceCulture);
            }
        }
        
        internal static string NoDefaultEncryptionKeySetToolTip {
            get {
                return ResourceManager.GetString("NoDefaultEncryptionKeySetToolTip", resourceCulture);
            }
        }
        
        internal static string NoNeedToCheckForUpdatesTooltip {
            get {
                return ResourceManager.GetString("NoNeedToCheckForUpdatesTooltip", resourceCulture);
            }
        }
        
        internal static string NoPremiumWarning {
            get {
                return ResourceManager.GetString("NoPremiumWarning", resourceCulture);
            }
        }
        
        internal static string NotFoundPageBody {
            get {
                return ResourceManager.GetString("NotFoundPageBody", resourceCulture);
            }
        }
        
        internal static string NotFoundPageTitle {
            get {
                return ResourceManager.GetString("NotFoundPageTitle", resourceCulture);
            }
        }
        
        internal static string NotFoundSafePageBody {
            get {
                return ResourceManager.GetString("NotFoundSafePageBody", resourceCulture);
            }
        }
        
        internal static string OfflineAccountBePatient {
            get {
                return ResourceManager.GetString("OfflineAccountBePatient", resourceCulture);
            }
        }
        
        internal static string OfflineAccountTitle {
            get {
                return ResourceManager.GetString("OfflineAccountTitle", resourceCulture);
            }
        }
        
        internal static string OldVersionTooltip {
            get {
                return ResourceManager.GetString("OldVersionTooltip", resourceCulture);
            }
        }
        
        internal static string OpenEncryptedFileOpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenEncryptedFileOpenDialogTitle", resourceCulture);
            }
        }
        
        internal static string OpenEncryptedToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OpenEncryptedToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string OpenFileColumnHeader {
            get {
                return ResourceManager.GetString("OpenFileColumnHeader", resourceCulture);
            }
        }
        
        internal static string OptionsChangePassphraseToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OptionsChangePassphraseToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string OptionsClearAllSettingsAndExitToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OptionsClearAllSettingsAndExitToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string OptionsLanguageToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OptionsLanguageToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string OptionsToolStripMenuItemText {
            get {
                return ResourceManager.GetString("OptionsToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string PassphrasePrompt {
            get {
                return ResourceManager.GetString("PassphrasePrompt", resourceCulture);
            }
        }
        
        internal static string PassphraseVerificationMismatch {
            get {
                return ResourceManager.GetString("PassphraseVerificationMismatch", resourceCulture);
            }
        }
        
        internal static string PasswordManagementListPageBody {
            get {
                return ResourceManager.GetString("PasswordManagementListPageBody", resourceCulture);
            }
        }
        
        internal static string PasswordManagementPageTitle {
            get {
                return ResourceManager.GetString("PasswordManagementPageTitle", resourceCulture);
            }
        }
        
        internal static string PasswordPolicyViolation {
            get {
                return ResourceManager.GetString("PasswordPolicyViolation", resourceCulture);
            }
        }
        
        internal static string PasswordResetLink {
            get {
                return ResourceManager.GetString("PasswordResetLink", resourceCulture);
            }
        }
        
        internal static string PasswordResetMailBody1 {
            get {
                return ResourceManager.GetString("PasswordResetMailBody1", resourceCulture);
            }
        }
        
        internal static string PasswordResetMailBodyButton {
            get {
                return ResourceManager.GetString("PasswordResetMailBodyButton", resourceCulture);
            }
        }
        
        internal static string PasswordResetMailSubject {
            get {
                return ResourceManager.GetString("PasswordResetMailSubject", resourceCulture);
            }
        }
        
        internal static string PasswordResetPageBody {
            get {
                return ResourceManager.GetString("PasswordResetPageBody", resourceCulture);
            }
        }
        
        internal static string PasswordResetPageTitle {
            get {
                return ResourceManager.GetString("PasswordResetPageTitle", resourceCulture);
            }
        }
        
        internal static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        internal static string PasswordStrengthBadTip {
            get {
                return ResourceManager.GetString("PasswordStrengthBadTip", resourceCulture);
            }
        }
        
        internal static string PasswordStrengthStrongTip {
            get {
                return ResourceManager.GetString("PasswordStrengthStrongTip", resourceCulture);
            }
        }
        
        internal static string PasswordStrengthUnacceptableTip {
            get {
                return ResourceManager.GetString("PasswordStrengthUnacceptableTip", resourceCulture);
            }
        }
        
        internal static string PasswordStrengthWeakTip {
            get {
                return ResourceManager.GetString("PasswordStrengthWeakTip", resourceCulture);
            }
        }
        
        internal static string PayPalReadMoreLink {
            get {
                return ResourceManager.GetString("PayPalReadMoreLink", resourceCulture);
            }
        }
        
        internal static string PremiumExpiresSoonMailBody0Html {
            get {
                return ResourceManager.GetString("PremiumExpiresSoonMailBody0Html", resourceCulture);
            }
        }
        
        internal static string PremiumExpiresSoonMailBody1Html {
            get {
                return ResourceManager.GetString("PremiumExpiresSoonMailBody1Html", resourceCulture);
            }
        }
        
        internal static string PremiumExpiresSoonMailBody2Html {
            get {
                return ResourceManager.GetString("PremiumExpiresSoonMailBody2Html", resourceCulture);
            }
        }
        
        internal static string PremiumExpiresSoonMailBody3Html {
            get {
                return ResourceManager.GetString("PremiumExpiresSoonMailBody3Html", resourceCulture);
            }
        }
        
        internal static string PremiumExpiresSoonMailSubject {
            get {
                return ResourceManager.GetString("PremiumExpiresSoonMailSubject", resourceCulture);
            }
        }
        
        internal static string PremiumFeatureToolTipText {
            get {
                return ResourceManager.GetString("PremiumFeatureToolTipText", resourceCulture);
            }
        }
        
        internal static string PremiumNeededForKeyShare {
            get {
                return ResourceManager.GetString("PremiumNeededForKeyShare", resourceCulture);
            }
        }
        
        internal static string ProgressContextCancelToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ProgressContextCancelToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string PromptActivationCode {
            get {
                return ResourceManager.GetString("PromptActivationCode", resourceCulture);
            }
        }
        
        internal static string PromptAddContact {
            get {
                return ResourceManager.GetString("PromptAddContact", resourceCulture);
            }
        }
        
        internal static string PromptBackLinkText {
            get {
                return ResourceManager.GetString("PromptBackLinkText", resourceCulture);
            }
        }
        
        internal static string PromptBuyNow {
            get {
                return ResourceManager.GetString("PromptBuyNow", resourceCulture);
            }
        }
        
        internal static string PromptBuyPremium {
            get {
                return ResourceManager.GetString("PromptBuyPremium", resourceCulture);
            }
        }
        
        internal static string PromptChange {
            get {
                return ResourceManager.GetString("PromptChange", resourceCulture);
            }
        }
        
        internal static string PromptCurrentPasswordText {
            get {
                return ResourceManager.GetString("PromptCurrentPasswordText", resourceCulture);
            }
        }
        
        internal static string PromptDeleteAxCryptIdText {
            get {
                return ResourceManager.GetString("PromptDeleteAxCryptIdText", resourceCulture);
            }
        }
        
        internal static string PromptEmailText {
            get {
                return ResourceManager.GetString("PromptEmailText", resourceCulture);
            }
        }
        
        internal static string PromptFileText {
            get {
                return ResourceManager.GetString("PromptFileText", resourceCulture);
            }
        }
        
        internal static string PromptKeepMeSignedIn {
            get {
                return ResourceManager.GetString("PromptKeepMeSignedIn", resourceCulture);
            }
        }
        
        internal static string PromptKnownContacts {
            get {
                return ResourceManager.GetString("PromptKnownContacts", resourceCulture);
            }
        }
        
        internal static string PromptLabelText {
            get {
                return ResourceManager.GetString("PromptLabelText", resourceCulture);
            }
        }
        
        internal static string PromptMonths {
            get {
                return ResourceManager.GetString("PromptMonths", resourceCulture);
            }
        }
        
        internal static string PromptMyAxCryptId {
            get {
                return ResourceManager.GetString("PromptMyAxCryptId", resourceCulture);
            }
        }
        
        internal static string PromptMySettings {
            get {
                return ResourceManager.GetString("PromptMySettings", resourceCulture);
            }
        }
        
        internal static string PromptNewEmail {
            get {
                return ResourceManager.GetString("PromptNewEmail", resourceCulture);
            }
        }
        
        internal static string PromptNewPasswordText {
            get {
                return ResourceManager.GetString("PromptNewPasswordText", resourceCulture);
            }
        }
        
        internal static string PromptNotificationsText {
            get {
                return ResourceManager.GetString("PromptNotificationsText", resourceCulture);
            }
        }
        
        internal static string PromptPasswordManager {
            get {
                return ResourceManager.GetString("PromptPasswordManager", resourceCulture);
            }
        }
        
        internal static string PromptSetNewPassword {
            get {
                return ResourceManager.GetString("PromptSetNewPassword", resourceCulture);
            }
        }
        
        internal static string PromptSharedWith {
            get {
                return ResourceManager.GetString("PromptSharedWith", resourceCulture);
            }
        }
        
        internal static string PromptSignIn {
            get {
                return ResourceManager.GetString("PromptSignIn", resourceCulture);
            }
        }
        
        internal static string PromptSignOut {
            get {
                return ResourceManager.GetString("PromptSignOut", resourceCulture);
            }
        }
        
        internal static string PromptSignUp {
            get {
                return ResourceManager.GetString("PromptSignUp", resourceCulture);
            }
        }
        
        internal static string PromptSubscription {
            get {
                return ResourceManager.GetString("PromptSubscription", resourceCulture);
            }
        }
        
        internal static string PromptVerifyEmail {
            get {
                return ResourceManager.GetString("PromptVerifyEmail", resourceCulture);
            }
        }
        
        internal static string PromptXecretsDescriptionText {
            get {
                return ResourceManager.GetString("PromptXecretsDescriptionText", resourceCulture);
            }
        }
        
        internal static string PromptXecretsNew {
            get {
                return ResourceManager.GetString("PromptXecretsNew", resourceCulture);
            }
        }
        
        internal static string PromptXecretsSearchText {
            get {
                return ResourceManager.GetString("PromptXecretsSearchText", resourceCulture);
            }
        }
        
        internal static string PromptXecretsSecretText {
            get {
                return ResourceManager.GetString("PromptXecretsSecretText", resourceCulture);
            }
        }
        
        internal static string PurchaseErrorSubscriptionTime {
            get {
                return ResourceManager.GetString("PurchaseErrorSubscriptionTime", resourceCulture);
            }
        }
        
        internal static string PurchasePageBody1 {
            get {
                return ResourceManager.GetString("PurchasePageBody1", resourceCulture);
            }
        }
        
        internal static string PurchasePageBody2 {
            get {
                return ResourceManager.GetString("PurchasePageBody2", resourceCulture);
            }
        }
        
        internal static string PurchasePageTitle {
            get {
                return ResourceManager.GetString("PurchasePageTitle", resourceCulture);
            }
        }
        
        internal static string PurchaseReceiptError {
            get {
                return ResourceManager.GetString("PurchaseReceiptError", resourceCulture);
            }
        }
        
        internal static string PurchaseReceiptErrorPageBody {
            get {
                return ResourceManager.GetString("PurchaseReceiptErrorPageBody", resourceCulture);
            }
        }
        
        internal static string PurchaseReceiptPageTitle {
            get {
                return ResourceManager.GetString("PurchaseReceiptPageTitle", resourceCulture);
            }
        }
        
        internal static string PurchaseReceiptSuccess {
            get {
                return ResourceManager.GetString("PurchaseReceiptSuccess", resourceCulture);
            }
        }
        
        internal static string PurchaseReceiptSuccessPageBody {
            get {
                return ResourceManager.GetString("PurchaseReceiptSuccessPageBody", resourceCulture);
            }
        }
        
        internal static string PurchaseVatPercent {
            get {
                return ResourceManager.GetString("PurchaseVatPercent", resourceCulture);
            }
        }
        
        internal static string PurgingActiveFiles {
            get {
                return ResourceManager.GetString("PurgingActiveFiles", resourceCulture);
            }
        }
        
        internal static string RecentFilesOpenToolStripMenuItemText {
            get {
                return ResourceManager.GetString("RecentFilesOpenToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string RecentFilesTabPageText {
            get {
                return ResourceManager.GetString("RecentFilesTabPageText", resourceCulture);
            }
        }
        
        internal static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        internal static string RegisterLink {
            get {
                return ResourceManager.GetString("RegisterLink", resourceCulture);
            }
        }
        
        internal static string RegisterPageBody {
            get {
                return ResourceManager.GetString("RegisterPageBody", resourceCulture);
            }
        }
        
        internal static string RegisterPageTitle {
            get {
                return ResourceManager.GetString("RegisterPageTitle", resourceCulture);
            }
        }
        
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        internal static string ReliabilityUpdateAvailableWarning {
            get {
                return ResourceManager.GetString("ReliabilityUpdateAvailableWarning", resourceCulture);
            }
        }
        
        internal static string RemoveRecentFileToolStripMenuItemText {
            get {
                return ResourceManager.GetString("RemoveRecentFileToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string SaveSecretErrorIsReadOnly {
            get {
                return ResourceManager.GetString("SaveSecretErrorIsReadOnly", resourceCulture);
            }
        }
        
        internal static string SecretsButtonToolTipText {
            get {
                return ResourceManager.GetString("SecretsButtonToolTipText", resourceCulture);
            }
        }
        
        internal static string SecretsWarningIsReadOnly {
            get {
                return ResourceManager.GetString("SecretsWarningIsReadOnly", resourceCulture);
            }
        }
        
        internal static string SecretsWarningIsSoonExpired {
            get {
                return ResourceManager.GetString("SecretsWarningIsSoonExpired", resourceCulture);
            }
        }
        
        internal static string SecureDeleteDialogTitle {
            get {
                return ResourceManager.GetString("SecureDeleteDialogTitle", resourceCulture);
            }
        }
        
        internal static string SecureDeleteToolStripMenuItemText {
            get {
                return ResourceManager.GetString("SecureDeleteToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string SecurityUpdateAvailableWarning {
            get {
                return ResourceManager.GetString("SecurityUpdateAvailableWarning", resourceCulture);
            }
        }
        
        internal static string SettingsDeletePageBody {
            get {
                return ResourceManager.GetString("SettingsDeletePageBody", resourceCulture);
            }
        }
        
        internal static string SettingsEmailPageBody {
            get {
                return ResourceManager.GetString("SettingsEmailPageBody", resourceCulture);
            }
        }
        
        internal static string SettingsNotificationsPageBody {
            get {
                return ResourceManager.GetString("SettingsNotificationsPageBody", resourceCulture);
            }
        }
        
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        internal static string SettingsPasswordPageBody {
            get {
                return ResourceManager.GetString("SettingsPasswordPageBody", resourceCulture);
            }
        }
        
        internal static string SharedWithUnverfiedMessageTitle {
            get {
                return ResourceManager.GetString("SharedWithUnverfiedMessageTitle", resourceCulture);
            }
        }
        
        internal static string SharedWithUnverifiedMessagePattern {
            get {
                return ResourceManager.GetString("SharedWithUnverifiedMessagePattern", resourceCulture);
            }
        }
        
        internal static string ShareKeysToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ShareKeysToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string ShowPasswordOptionPrompt {
            get {
                return ResourceManager.GetString("ShowPasswordOptionPrompt", resourceCulture);
            }
        }
        
        internal static string SiteRestartWarning {
            get {
                return ResourceManager.GetString("SiteRestartWarning", resourceCulture);
            }
        }
        
        internal static string SubscriptionsErrorAmount {
            get {
                return ResourceManager.GetString("SubscriptionsErrorAmount", resourceCulture);
            }
        }
        
        internal static string SubscriptionsSuccessAdd {
            get {
                return ResourceManager.GetString("SubscriptionsSuccessAdd", resourceCulture);
            }
        }
        
        internal static string TextCheckEmailAndSpam {
            get {
                return ResourceManager.GetString("TextCheckEmailAndSpam", resourceCulture);
            }
        }
        
        internal static string TextPreferenceCritical {
            get {
                return ResourceManager.GetString("TextPreferenceCritical", resourceCulture);
            }
        }
        
        internal static string TextPreferenceDecline {
            get {
                return ResourceManager.GetString("TextPreferenceDecline", resourceCulture);
            }
        }
        
        internal static string TextPreferenceUnknown {
            get {
                return ResourceManager.GetString("TextPreferenceUnknown", resourceCulture);
            }
        }
        
        internal static string TextPreferenceUpdate {
            get {
                return ResourceManager.GetString("TextPreferenceUpdate", resourceCulture);
            }
        }
        
        internal static string TitleAxCryptIdSignInText {
            get {
                return ResourceManager.GetString("TitleAxCryptIdSignInText", resourceCulture);
            }
        }
        
        internal static string TitleCreateAxCryptIdTitle {
            get {
                return ResourceManager.GetString("TitleCreateAxCryptIdTitle", resourceCulture);
            }
        }
        
        internal static string TitleMainWindow {
            get {
                return ResourceManager.GetString("TitleMainWindow", resourceCulture);
            }
        }
        
        internal static string TitleSignInToAxCrypt {
            get {
                return ResourceManager.GetString("TitleSignInToAxCrypt", resourceCulture);
            }
        }
        
        internal static string TitleWindowSignInStatus {
            get {
                return ResourceManager.GetString("TitleWindowSignInStatus", resourceCulture);
            }
        }
        
        internal static string ToolTipPremiumNeededForSecrets {
            get {
                return ResourceManager.GetString("ToolTipPremiumNeededForSecrets", resourceCulture);
            }
        }
        
        internal static string TransactionHistoryTitle {
            get {
                return ResourceManager.GetString("TransactionHistoryTitle", resourceCulture);
            }
        }
        
        internal static string TrayBalloonTooltip {
            get {
                return ResourceManager.GetString("TrayBalloonTooltip", resourceCulture);
            }
        }
        
        internal static string TryBrokenFileToolStripMenuItemText {
            get {
                return ResourceManager.GetString("TryBrokenFileToolStripMenuItemText", resourceCulture);
            }
        }
        
        internal static string UnknownCrypto {
            get {
                return ResourceManager.GetString("UnknownCrypto", resourceCulture);
            }
        }
        
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        internal static string UnknownFileStatus {
            get {
                return ResourceManager.GetString("UnknownFileStatus", resourceCulture);
            }
        }
        
        internal static string UnknownLogOn {
            get {
                return ResourceManager.GetString("UnknownLogOn", resourceCulture);
            }
        }
        
        internal static string UnrecognizedError {
            get {
                return ResourceManager.GetString("UnrecognizedError", resourceCulture);
            }
        }
        
        internal static string UnregisterMailBody1 {
            get {
                return ResourceManager.GetString("UnregisterMailBody1", resourceCulture);
            }
        }
        
        internal static string UnregisterMailBody2 {
            get {
                return ResourceManager.GetString("UnregisterMailBody2", resourceCulture);
            }
        }
        
        internal static string UnregisterMailSubject {
            get {
                return ResourceManager.GetString("UnregisterMailSubject", resourceCulture);
            }
        }
        
        internal static string UpdatingStatus {
            get {
                return ResourceManager.GetString("UpdatingStatus", resourceCulture);
            }
        }
        
        internal static string UpgradePromptText {
            get {
                return ResourceManager.GetString("UpgradePromptText", resourceCulture);
            }
        }
        
        internal static string UserSettingsFormatChangeNeedsReset {
            get {
                return ResourceManager.GetString("UserSettingsFormatChangeNeedsReset", resourceCulture);
            }
        }
        
        internal static string VerifyPasswordPrompt {
            get {
                return ResourceManager.GetString("VerifyPasswordPrompt", resourceCulture);
            }
        }
        
        internal static string WatchedFolderColumnHeaderText {
            get {
                return ResourceManager.GetString("WatchedFolderColumnHeaderText", resourceCulture);
            }
        }
        
        internal static string WatchedFoldersOpenExplorerHereMenuItemText {
            get {
                return ResourceManager.GetString("WatchedFoldersOpenExplorerHereMenuItemText", resourceCulture);
            }
        }
        
        internal static string WatchedFoldersRemoveMenuItemText {
            get {
                return ResourceManager.GetString("WatchedFoldersRemoveMenuItemText", resourceCulture);
            }
        }
        
        internal static string WatchedFoldersTabPageText {
            get {
                return ResourceManager.GetString("WatchedFoldersTabPageText", resourceCulture);
            }
        }
        
        internal static string WelcomeMailBody0Html {
            get {
                return ResourceManager.GetString("WelcomeMailBody0Html", resourceCulture);
            }
        }
        
        internal static string WelcomeMailBody1Html {
            get {
                return ResourceManager.GetString("WelcomeMailBody1Html", resourceCulture);
            }
        }
        
        internal static string WelcomeMailBody2Html {
            get {
                return ResourceManager.GetString("WelcomeMailBody2Html", resourceCulture);
            }
        }
        
        internal static string WelcomeMailBody3Html {
            get {
                return ResourceManager.GetString("WelcomeMailBody3Html", resourceCulture);
            }
        }
        
        internal static string WelcomeMailSubject {
            get {
                return ResourceManager.GetString("WelcomeMailSubject", resourceCulture);
            }
        }
        
        internal static string WelcomeToAxCrypt {
            get {
                return ResourceManager.GetString("WelcomeToAxCrypt", resourceCulture);
            }
        }
        
        internal static string WelcomeToAxCryptTitle {
            get {
                return ResourceManager.GetString("WelcomeToAxCryptTitle", resourceCulture);
            }
        }
        
        internal static string WipeFileSelectFileDialogTitle {
            get {
                return ResourceManager.GetString("WipeFileSelectFileDialogTitle", resourceCulture);
            }
        }
        
        internal static string WorkingFileStatus {
            get {
                return ResourceManager.GetString("WorkingFileStatus", resourceCulture);
            }
        }
        
        internal static string WrongPassphrase {
            get {
                return ResourceManager.GetString("WrongPassphrase", resourceCulture);
            }
        }
        
        internal static string WrongVerificationCode {
            get {
                return ResourceManager.GetString("WrongVerificationCode", resourceCulture);
            }
        }
        
        internal static string WrongVerificationCodeFormat {
            get {
                return ResourceManager.GetString("WrongVerificationCodeFormat", resourceCulture);
            }
        }
    }
}
